# version: "3"
# services:
#   auto-healer:
#     build: .
#     container_name: auto-healer_from_compose
#     volumes:
#       - ./logs:/app/logs


services:
  auto-healer:
    image: dockermjrr/auto-healer:1.1
    container_name: auto-healer-container
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped