---

- name: Create application directory
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Ensure application is started
  community.docker.docker_compose_v2:
    project_src: "{{ app_directory }}"
    state: present
    pull: always